all: 
  hosts: 
    vqfx1:
      ansible_host: 127.0.0.1
      ansible_ssh_port: 2200
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
      ansible_user: vagrant
  children:
    junos:
      hosts:
        vqfx1:
    l2device:
      hosts:
        vqfx1: