network_resources:
    acl_interfaces:
    -   name: Loopback0
    -   access_groups:
        -   afi: ipv4
        name: Loopback1
    -   name: GigabitEthernet0/0
    -   name: GigabitEthernet0/1
    -   name: GigabitEthernet0/2
    interfaces:
    -   enabled: true
        name: loopback0
    -   description: new loopback interface
        enabled: true
        name: loopback1
    -   duplex: auto
        enabled: true
        name: GigabitEthernet0/0
        speed: auto
    -   duplex: auto
        enabled: true
        name: GigabitEthernet0/1
        speed: auto
    -   description: new loopback interface gi0/2
        duplex: auto
        enabled: false
        name: GigabitEthernet0/2
        speed: auto
    l2_interfaces:
    -   name: GigabitEthernet0/0
    -   name: GigabitEthernet0/1
    -   name: GigabitEthernet0/2
    l3_interfaces:
    -   ipv4:
        -   address: 10.255.255.2 255.255.255.255
        name: loopback0
    -   ipv4:
        -   address: 2.2.2.2 255.255.255.255
        name: loopback1
    -   ipv4:
        -   address: 172.16.1.102 255.255.255.0
        name: GigabitEthernet0/0
    -   ipv4:
        -   address: 10.10.100.102 255.255.255.0
        name: GigabitEthernet0/1
    -   name: GigabitEthernet0/2
    lag_interfaces:
    -   name: GigabitEthernet0/0
    -   name: GigabitEthernet0/1
    -   name: GigabitEthernet0/2
    static_routes:
    -   address_families:
        -   afi: ipv4
            routes:
            -   dest: 0.0.0.0/32
                next_hops:
                -   forward_router_address: 172.16.1.1
        vrf: mgmt
    - {}
