network_resources:
    acl_interfaces:
    -   name: Loopback0
    -   name: Loopback2
    -   name: GigabitEthernet0/0
    -   name: GigabitEthernet0/1
    interfaces:
    -   enabled: true
        name: loopback0
    -   description: ANSIBLE CONFIGURED
        enabled: true
        name: loopback2
    -   duplex: auto
        enabled: true
        name: GigabitEthernet0/0
        speed: auto
    -   duplex: auto
        enabled: true
        name: GigabitEthernet0/1
        speed: auto
    l2_interfaces:
    -   name: GigabitEthernet0/0
    -   name: GigabitEthernet0/1
    l3_interfaces:
    -   ipv4:
        -   address: 10.255.255.1 255.255.255.255
        name: loopback0
    -   ipv4:
        -   address: 10.199.199.1 255.255.255.255
        name: loopback2
    -   ipv4:
        -   address: 172.16.1.101 255.255.255.0
        name: GigabitEthernet0/0
    -   ipv4:
        -   address: 10.10.100.101 255.255.255.0
        name: GigabitEthernet0/1
    lag_interfaces:
    -   name: GigabitEthernet0/0
    -   name: GigabitEthernet0/1
    static_routes:
    -   address_families:
        -   afi: ipv4
            routes:
            -   dest: 0.0.0.0/32
                next_hops:
                -   forward_router_address: 172.16.1.1
        vrf: mgmt
    - {}
