intfs:
    acl_interfaces:
    -   name: MgmtEth0/0/CPU0/0
    acls: []
    lacp: {}
    lag_interfaces: []
    lldp_global: {}
    static_routes:
    -   address_families:
        -   afi: ipv4
            routes:
            -   dest: 0.0.0.0/0
                next_hops:
                -   forward_router_address: 172.16.1.1
            safi: unicast
        vrf: mgmt
