intfs:
    interfaces:
    -   description: first interface
        enabled: false
        name: GigabitEthernet0/0/0/0
        speed: 1000
    l2_interfaces:
    -   name: GigabitEthernet0/0/0/0
    l3_interfaces:
    -   ipv4:
        -   address: 10.10.100.104 255.255.255.0
        name: GigabitEthernet0/0/0/0
    lacp: {}
    lacp_interfaces:
    -   name: GigabitEthernet0/0/0/0
    lag_interfaces: []
    lldp_global: {}
    lldp_interfaces:
    -   name: GigabitEthernet0/0/0/0
