network_resources:
    acl_interfaces:
    -   name: GigabitEthernet1
    -   name: GigabitEthernet2
    -   name: GigabitEthernet3
    -   access_groups:
        -   afi: ipv4
        name: GigabitEthernet4
    -   name: GigabitEthernet1
    interfaces:
    -   enabled: true
        name: GigabitEthernet1
    -   enabled: false
        name: GigabitEthernet2
    -   enabled: false
        name: GigabitEthernet3
    -   enabled: false
        name: GigabitEthernet4
    l2_interfaces:
    -   name: GigabitEthernet1
    -   name: GigabitEthernet2
    -   name: GigabitEthernet3
    -   name: GigabitEthernet4
    l3_interfaces:
    -   ipv4:
        -   address: 172.16.1.103 255.255.255.0
        name: GigabitEthernet1
    -   name: GigabitEthernet2
    -   name: GigabitEthernet3
    -   name: GigabitEthernet4
    lag_interfaces:
    -   name: GigabitEthernet1
    -   name: GigabitEthernet2
    -   name: GigabitEthernet3
    -   name: GigabitEthernet4
    static_routes:
    -   address_families:
        -   afi: ipv4
            routes:
            -   dest: 0.0.0.0/32
                next_hops:
                -   forward_router_address: 172.16.1.1
        vrf: mgmt
    - {}
