name: Webhook to KVM Tower
on: push
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: trigger workflow_template on tower
        run: |
          curl \
            -H "Authorization: Bearer ${{ secrets.TOWER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{ "extra_vars": {"foo": "bar"}, "limit": "iosv1,iosv2" }' \
            -X POST ${{ secrets.TOWER_URL }}
