name: Webhook to KVM Tower
on: 
  push:
    tags:
      - '.*'
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: trigger workflow_template on tower
        run: |
          curl \
            -H "Authorization: Bearer ${{ secrets.TOWER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{ "extra_vars": {"github_event": "${{ github.event }}"}, \
              "limit": "${{ github.ref }}" }' \
            -X POST ${{ secrets.TOWER_URL }}
