- name: Web Request Action
  uses: Satak/webrequest-action@v1.2.3

  on: push

  with:
    url: https://kvm1.maxrainer.net:7443/api/v2/workflow_job_templates/46/github/
    methode: POST
    headers: '{"Authentication": "Token ${{ secrets.TOWER_TOKEN }}"}'
    payload: '{ "git_tag": "foo" }'

    


