name: Webhook to KVM Tower
on: push
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: except all certs
        run: |
          export
      - name: webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: '{"repository": "joelwmale/webhook-action",
                    "xSecretx": "${{ secrets.TOWER_TOKEN }}"}'
          body: '{"event": "deployment", "repository": "joelwmale/webhook-action"}'

