name: Webhook to KVM Tower
on: push
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: except all certs
        run: |
          export
      - name: webhook
        uses: joelwmale/webhook-action@master
        with:
          url: "https://kvm1.maxrainer.net:7443/api/v2/workflow_job_templates/46/github/"
          headers: '{"repository": "joelwmale/webhook-action",
                    "Authorization: Bearer ${{ secrets.TOWER_TOKEN }}"}'
          body: '{"event": "deployment", "repository": "joelwmale/webhook-action"}'

