name: Webhook to KVM Tower
on: push
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: trigger workflow_template on tower
        uses: wei/curl@v1.1.1
        with: 
          args: -H "Authorization: Bearer ${{ secrets.TOWER_TOKEN }}" -d '{"foo": "bar"}' -X POST ${{ secrets.TOWER_URL }}
