name: Webhook to KVM Tower
on: push
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: trigger workflow_template on tower
        run: |
          curl -H "Authorization: Bearer ${{ secrets.TOWER_TOKEN }}" -H "Content-Type: application/json" -d '{"foo": "bar"}' -X POST ${{ secrets.TOWER_URL }}
