name: Webhook to KVM Tower
on: 
  push:
    tags:
      - c*.*
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: trigger workflow_template on tower
        run: |
          curl \
            -H "Authorization: Bearer ${{ secrets.TOWER_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{ "extra_vars": {"github_event_name": "${{ github.event_name }}", \
              "github_action": "${{ github.action }}" }, \
              "limit": "${{ github.event.head_commit.message }}" \
            -X POST ${{ secrets.TOWER_URL }}
