name: Webhook to KVM Tower
on: push
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: except all certs
        run: |
          export
      - name: trigger Workflow Template on Tower
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.TOWER_URL }}
          headers: '{"repository": "joelwmale/webhook-action",
                    "Authorization: Bearer ${{ secrets.TOWER_TOKEN }}"}'
          body: '{"extra_vars": {"foo": "bar"} }'

