name: Webhook to KVM Tower
on: push
jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: except all certs
        run: |
          export NODE_TLS_REJECT_UNAUTHORIZED='0'
          export
      - name: Web Request Action
        uses: Satak/webrequest-action@v1.2.3
        with:
          url: https://kvm1.maxrainer.net:7443/api/v2/workflow_job_templates/46/github/
          methode: POST
          headers: '{"xSecretx": "${{ secrets.TOWER_TOKEN }}"}'
          payload: '{ "git_tag": "foo" }'

    


